name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Remove yarn.lock
      run: rm -f yarn.lock
    - name: Install Packages
      run: yarn
    - name: Run ESLint
      run: npm run lint:check
    - name: Run type checking
      run: npm run ts:check
    - name: Run unit test
      run: npm run test:cov
